name: Deploy

on:
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Build Nest.js app
              run: npm run build

            # - name: Deploy to VPS
            #   uses: easingthemes/ssh-deploy@v2
            #   with:
            #       host: ${{ secrets.HOST }}
            #       username: ${{ secrets.USERNAME }}
            #       privateKey: ${{ secrets.PRIVATE_KEY }}
            #       port: ${{ secrets.PORT }}
            #       local: 'dist' # Путь к собранному приложению
            #       remote: '/var/www/your-app' # Путь на сервере, куда нужно развернуть приложение
